---
config:
  kanban:
    ticketBaseUrl: 'https://github.com/paco-ruvalcaba/mermaid_kanban/blob/master/#TICKET#'
---
kanban
  s1[Semana 1]
    ev1[Evidencia semana 1]@{ priority: 'High' }
    hdm203[Castillos Verdaderos pg. 203-206]@{ ticket: t203.md}
    hdm207[Señoras y caballeros 207-210]
  s2[Semana 2]
    ev1[Evidencia semana 2]
  s3[Semana 3]
    ev1[Evidencia semana 3]
